language: elixir
elixir:
  - '1.8'
env:
  - MIX_ENV=test
before_install:
  - chmod +x travis_merge_script.sh
  - chmod +x publish.sh
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
script:
  - mix build_travis
after_success:
  - ./travis_merge_script.sh
  - ./publish.sh