language: elixir
elixir:
  - '1.6.0'
otp_release:
  - '20.2.2'
before_install:
  - chmod +x travis_merge_script.sh
  - chmod +x publish.sh
  - mix local.hex --force
  - mix deps.get
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
script:
  - mix test && MIX_ENV=test mix coveralls.travis && mix docs
after_success:
  - mix format mix.exs "lib/**/*.{ex,exs}" "test/**/*.{ex,exs}" "lib/*.{ex,exs}" "test/*.{ex,exs}"
  - ./travis_merge_script.sh
  - ./publish.sh